# Generated by Django 5.2.4 on 2025-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvexa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
