# Generated by Django 5.2.4 on 2025-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvexa', '0002_contactform_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
