# Generated by Django 5.2.4 on 2025-07-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solvexa', '0003_alter_contactform_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-submitted_at']},
        ),
    ]
