# Generated by Django 5.2.4 on 2025-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvexa', '0004_alter_contactform_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
